### ISSUE TITLE
Automatically use `location.pathname` as default for user/repository, if available

### ISSUE THREAD

**Issue by fregante** [sindresorhus/linkify-issues#10]
What do you think about including a check for `location.pathname` here if it's in a browser?

https://github.com/sindresorhus/linkify-issues/blob/162efcb499f3d0a1420246676ffc2f063c65e9ba/index.js#L53-L55

Example:

```js
if (!(options.user && options.repository)) {
	if (typeof location === 'undefined') {
		throw new Error('Missing required `user` and `repository` options'); 
	}
	const [, user, repository] = location.pathname.split('/');
	options.user = user;
	options.repository = repository;
}
```

**Comment by sindresorhus** [comment]
This feels too specific for Refined GitHub's use-case. Most other uses of this package would be for linkifying URLs at a non-GitHub site.

**Comment by fregante** [comment]
Partially true, it's specific to code run on GitHub websites (i.e. web extensions). But in practice RG is the only user: 

- https://github.com/sindresorhus/linkify-issues/network/dependents
- https://www.npmjs.com/package/linkify-issues?activeTab=dependents

I don't feel strongly about this anyway, I just felt that this logic could be helpful here.

**Comment by sindresorhus** [comment]
I think this package should stay agnostic to where it's being used from.

**Comment by fregante** [comment]
Fine, I'm gonna have my own version: [fregante/linkify-issues-with-blackjack-and-hookers](https://www.youtube.com/watch?v=BjDebmqFRuc)
